id: P005543
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20090
  title: གཏེར་ཆེན་ཆོས་རྗེ་གླིང་པའི་རྟོགས་པ་བརྗོད་པ་རྗེ་བཙུན་མཆོག་གི་ཞལ་ལུང་དད་པའི་འཁྲི་ཤིང་།
  author: ''
  volumes:
    202cd1954cfa40f693cdd7956ee65f62:
      image_group_id: I8LS20092
      title: ''
      volume_number: 1
      total_pages: 375
      base_file: v001.txt
