id: P005543
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:58:30.228058
source_metadata:
  id: bdr:W8LS20090
  title: གཏེར་ཆེན་ཆོས་རྗེ་གླིང་པའི་རྟོགས་པ་བརྗོད་པ་རྗེ་བཙུན་མཆོག་གི་ཞལ་ལུང་དད་པའི་འཁྲི་ཤིང་།
  author: ''
  volumes:
    202cd1954cfa40f693cdd7956ee65f62:
      image_group_id: I8LS20092
      title: ''
      volume_number: 1
      total_pages: 375
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
