id: opecha:P005543
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20090
  title: གཏེར་ཆེན་ཆོས་རྗེ་གླིང་པའི་རྟོགས་པ་བརྗོད་པ་རྗེ་བཙུན་མཆོག་གི་ཞལ་ལུང་དད་པའི་འཁྲི་ཤིང་།
  volume: ''
  author: ''
