id: IBB6CB711
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:22:30+00:00'
last_modified: '2022-06-08T04:48:07.185872+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20090
  title: གཏེར་ཆེན་ཆོས་རྗེ་གླིང་པའི་རྟོགས་པ་བརྗོད་པ་རྗེ་བཙུན་མཆོག་གི་ཞལ་ལུང་དད་པའི་འཁྲི་ཤིང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F22F:
      image_group_id: I8LS20092
      title: ''
      total_pages: 375
      order: 1
      base_file: F22F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
